name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  runner-job:

    runs-on: ubuntu-latest
    services:
      postrges:
        image: postgres
        env:
          POSTGRES_PASSWORD: 1111
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytz==2020.1
        pip install python-slugify==4.0.1
        pip install Pillow==7.2.0
        pip install argon2-cffi==20.1.0
        pip install whitenoise==5.2.0
        pip install unidecode==1.1.1
        pip install django==3.1.1
        pip install django-environ==0.4.5
        pip install django-model-utils==4.0.0
        pip install django-allauth==0.42.0
        pip install django-crispy-forms==1.9.2
        pip install django-autoslug==1.9.8
        pip install django-countries==6.0
        pip install gunicorn==20.0.4
        pip install psycopg2==2.8.6
        pip install Collectfast==2.2.0
        pip install django-anymail[mailgun]==8.0
        pip install django-redis==4.12.1
        pip install pycodestyle==2.7.0
        pip install flake8==3.8.3
        pip install coverage==5.3
        pip install black==20.8b1
        pip install pylint-django==2.3.0
        pip install pre-commit==2.7.1
        pip install factory-boy==3.0.1
        pip install django-debug-toolbar==3.1
        pip install django-extensions==3.0.9
        pip install django-coverage-plugin==1.8.0
        pip install pytest-django==3.10.0

    - name: Run Tests
      run: |
        coverage run -m pytest
